### ISSUE TITLE
Getty over SSH?

### ISSUE THREAD

**Issue by Kodmod** [mmgen/mmgen-geek-tools#1]
The only problem with this script, like CRYPTROOT_ENABLE with the Armbian-build options, is that you cannot connect to the device if it has no ethernet port. I think the easiest way to take care of this would be to enable Getty instead of Dropbear SSH. That way, you can decrypt the FS over serial, and then log in normally over WiFi or USB (or serial again). This should make it compatible with everything.

**Comment by mmgen** [comment]
Good point. I'll look into adding serial unlock/login. But it would be best to leave the ethernet functionality in too so that users have a choice. Most Armbian-supported boards I know of have an ethernet port, and that's the most familiar option for most users.

**Comment by Kodmod** [comment]
>But it would be best to leave the ethernet functionality in too so that users have a choice.
Agreed.

**Comment by mmgen** [comment]
Support for disk unlocking / login from the serial console added with commit 73bbc47.

Enabling this feature has no effect on dropbear/SSH unlocking, though it disables unlocking from the VT.
