### ISSUE TITLE
Add a passphrase prompt

### ISSUE THREAD

**Issue by whollacsek** [mmgen/mmgen-geek-tools#2]
@mmgen Thanks for this script it works great!

It would be even better if we can avoid the need to type such command to unlock:
```
$ ssh -p 2222 root@192.168.0.88 'echo -n abc > /lib/cryptsetup/passfifo'
```

I just tried the following on buzybox and it successfully prompted for the passphrase when I tried to log in with a 2nd shell.
```
# echo "/lib/cryptsetup/askpass "passphrase: " > /lib/cryptsetup/passfifo" > .profile
# echo "exit" >> .profile
```

If this is a good solution I'd love to see it included by default.

**Comment by mmgen** [comment]
Thanks, clever idea.  I'll consider adding this to the script.

**Comment by mmgen** [comment]
Feature has been added (using slightly different implementation) in commit 6c32f2e05
