### ISSUE TITLE
Doc improvements

### ISSUE THREAD

**Issue by whollacsek** [mmgen/mmgen-geek-tools#3]
Overall the script is quite understandable, here are some suggestions to improve the usability and documentation:
- Add at end of the script a message to explain to the user they must login **with** the root user **using** the port 2222
- Add more explanations on the options -s and -z, maybe with a short hint to some use cases

**Comment by mmgen** [comment]
Good suggestions.

**Comment by mmgen** [comment]
Suggestions addressed in commit 6c32f2e0
