### ISSUE TITLE
Doesn't seem to work on BPI-M2 Zero

### ISSUE THREAD

**Issue by Kodmod** [mmgen/mmgen-geek-tools#5]
The script executes fine and appears to create the partitions and FS properly. But after inserting the SD card into the device, the LED turns on for 1-2 seconds and then turns off completely, instead of the typical armbian heartbeat pattern. I also cannot communicate with it via the serial console.

Any idea why this might be the case? I've attached the verbose terminal output.
[terminal.txt](https://github.com/mmgen/mmgen-geek-tools/files/6289433/terminal.txt)

**Comment by mmgen** [comment]
You should be getting some output on the serial console, at least from u-boot, even if the kernel fails to start. Do you have your USB-UART dongle wired up correctly? Are you seeing the u-boot messages on the serial console when using the stock image?

**Comment by Kodmod** [comment]
USB-UART dongle? Could this not work over USB, like as it does normally with the `g_serial` module?

**Comment by mmgen** [comment]
No, of course, that's all configured much later, in the userspace.

Here's some info to get you started:

Info on using the serial console (for Orange Pi, but generally applicable): https://linux-sunxi.org/UART

Hardware info for your board: https://wiki.banana-pi.org/Banana_Pi_BPI-M2_ZERO

Pinouts for Raspberry Pi (Banana Pi uses the same ones): https://pinout.xyz

You'll be connecting to pins 6,8 and 10 on the GPIO. Note that RX goes to TX and TX to RX. And ground to ground, of course.

**Comment by Kodmod** [comment]
Yep, thats the problem. I got spoiled by armbian and thought it would be from USB :P
Although, do you think this functionality could be made to work un uboot? [This mailing list](http://u-boot.10912.n7.nabble.com/U-Boot-USB-serial-console-under-Uboot-td42855.html) hints that it is possible but I'm not sure if it's a matter of just loading a driver (`usbtty`) or recompiling everything. I have no knowledge of how uboot works.

**Comment by mmgen** [comment]
From the mailing list:
> There is usbtty support in u-boot but only for some OMAP1 devices (although it is broken in the current release) and for some MPC devices. Unfortunately, I don't believe that this is currently supported for OMAP3. Therefore, I think that you are going to need an RS232-to-USB dongle for your PC in order to interact with u-boot.

Very unlikely you could get this to work. Much simpler to just buy a dongle.

It's also possible to compile in the g_serial module (described here: https://linux-sunxi.org/USB_Gadget/Serial), but that means recompiling the kernel, and you won't see the early startup messages before the kernel is loaded.

I recommend getting the dongle. It's well worth it.

**Comment by Kodmod** [comment]
My armbian image is actually a custom build with `g_ether` and `g_serial` added as modules. Are you saying that if I compile in `g_serial` (not as a module), I could access the USB serial console and decrypt it that way?

At what point does the decryption happen? If it's after the kernel is loaded, then surely I should be able the load the `g_serial` module before the decryption prompt, right?

`g_ether` is out of the question because it requires a lot of setup and dependance on other things like DHCP.

BTW you can close the issue of you'd like since this is probably outside the scope for this script.

**Comment by mmgen** [comment]
Yes, you're right, compiling in `g_serial` would be the easiest approach. Since it's part of the kernel, it would already be loaded before the decryption prompt, which happens in the initrd userspace. The downside with `g_serial` is that you might not be able to reconfigure your USB link as a network link once you've booted up, if that's what you intend to do.

**Comment by Kodmod** [comment]
> The downside with g_serial is that you might not be able to reconfigure your USB link as a network link once you've booted up, if that's what you intend to do.
I completely forgot about that. Is there a way I can load it as a `g_serial` module before the decryption prompt (so I can then `rmmod` it)?

**Comment by mmgen** [comment]
You can add it to `/etc/initramfs-tools/modules`, run `update-initramfs` and it will be included in the initrd.

**Comment by Kodmod** [comment]
Just chrooted into the fs and found that `g_serial` was already there. Not sure what I could do at this point. I appreciate all your help though.

**Comment by mmgen** [comment]
Oh that's right. I see it in the terminal printout you sent me.

I'd recommend testing whether you can get the serial console working over USB with the stock image. Then take it from there.

**Comment by mmgen** [comment]
Commit cf93a045 - disk unlocking via SSH over USB (USB gadget, g_ether)

- both static and dynamic (DHCP) IP are supported
- interface is configured both in initrd and booted system

**Comment by Kodmod** [comment]
Whoa, no way.
I'll give this a shot soon. You might want to mention in the documentation that the armbian image itself must have `g_ether` built as a module.

**Comment by mmgen** [comment]
All the prebuilt images have `g_ether` as a module, don't they?

**Comment by Kodmod** [comment]
I wasn't aware that they added the `g_ether` module to the prebuilt images.
This might be a recent inclusion, and a welcome one at that.

**Comment by mmgen** [comment]
I'm testing on only 2 boards, the Rock Pi 4 and the Orange Pi PC2, but both of them have it.

**Comment by Kodmod** [comment]
I tried the update but unfortunately, I couldn't get it to work. The issue is that the device doesn't even appear to boot properly. As before, the LED lights up for 1 second and then turns off indefinitely. My computer doesn't even detect it as a USB device either.
So the problem likely isn't even `g_serial` or `g_ether` but the booting. Maybe I could try to do this manually (as you posted on the armbian forum) instead of using the script and see where things go wrong.

**Comment by mmgen** [comment]
Yep, looks like the problem's very early on in the boot process. With a USB dongle you could get some useful diagnostics, by the way, so you might look into acquiring one. I also plan to get my hands on some more boards to expand the range of hardware my script supports.

**Comment by Kodmod** [comment]
I highly recommend the BPI-M2 Zero. It's cheap, has the form factor of Rasp-pi zero, has wireless, and is quad-core with 512 MB of RAM. BTW I got these messages (warnings?) when I ran the latest version of the script:
`./armbian_rootenc_setup.sh: line 491: [: ==: unary operator expected`

**Comment by mmgen** [comment]
Thanks, I'll put the M2 Zero on my buy list.
And thanks for the error report. That was a bug in the script. I just pushed the fix to the repository.
