### ISSUE TITLE
lsblk: /dev/mapper/No: not a block device

### ISSUE THREAD

**Issue by lsafelix75** [mmgen/mmgen-geek-tools#8]
Hi,

I am getting the above error on Orange Pi Lite. Any cause that could throw this error? Thanks

                    For detailed usage information,
                        invoke with the '-h' switch

get_armbian_image                OK
apt_install_host                 OK
close_loopmount                  OK
lsblk: /dev/mapper/No: not a block device
lsblk: /dev/mapper/No: not a block device
umount_target                    OK
remove_build_dir                 OK
Will write to target /dev/sda (     SD_Card_Reader 7.4G)
check_sdcard_name_and_params     OK
create_build_dir                 OK

**Comment by mmgen** [comment]
The error seems to be produced by _get_device_maps(), which is called by _preclean()

Try running this on your Armbian host system:

    $ sudo dmsetup ls

The output should be a list of device names and device numbers in parentheses, with no additional output.

By the way, was the build successful? The script is untested for the Orange Pi Lite.

**Comment by mmgen** [comment]
> Hi,
> 
> I am getting the above error on Orange Pi Lite. Any cause that could throw this error? Thanks

I've fixed the problem. Give the script a try again. If everything's successful, let me know and I'll add your board to the supported list.
